export default {
  auth: {
    signIn: 'Sign in',
    signUp: 'Sign up for EMQX Cloud',
    signUpXmeter: 'Sign up for XMeter Cloud',
    freeTrial: 'Start free trial',
    email: 'Email',
    password: 'Password',
    forgot: 'Forgot your password',
    back: 'Back',
    fullName: 'Full Name',
    userName: 'Full Name',
    firstName: 'First Name',
    lastName: 'Last Name',
    phoneOnlyCN: 'Phone Number',
    phone: 'Phone Number',
    company: 'Company',
    organization: 'Organization',
    useCase: 'Use Case',
    country: 'Country or Region',
    os: 'OS',
    subscribe: 'I would like to receive email updates from EMQ.',
    alreadyRegistered: '{signIn}',
    notRegistered: "Don't have an account? {signUp}",
    checkEmail: 'Please check the activation email in your mailbox to complete the registration.',
    activatedSuccess: 'Activated successfully, and you will be redirected to the login page......',
    expired: 'Your verification url seems to have expired.',
    otherDomainTips: 'Your account is from EMQ Chinese site, please go to {0}',
    ssoErrorTips: 'Only Chinese users are supported to log in to the discourse, Please {0} again.',
    activating: 'Please wait',
    passwordMust: 'Your password must',
    characters: 'Be a minimum of 8 characters',
    passwordInclude: 'Contains at least two of the following: letters, numbers, symbols',
    passwordErrorTips: 'Password you entered is insecure',
    or: 'Or sign in with',
    signinWithWeChat: 'SIGN IN WITH WECHAT',
    signinWithGoogle: 'Google',
    readAgreement: 'I accept the {termsOfService} and the {privacyPolicy}',
    termsOfService: 'Terms of Use',
    privacyPolicy: 'Privacy Policy',
    termsLink: '/policy/terms-of-use',
    agreementTips: 'Please accept the terms to continue',
    headTitle: {
      signIn: 'Sign In',
      signUp: 'Sign Up',
      signOut: 'Sign Out',
      forgot: 'Forgot Password',
      mailReset: 'Reset Password',
      reset: 'Reset Password',
      set: 'Set Password',
      active: 'Activation',
    },
    forgotPassword: {
      title: 'Forgot password',
      tip: 'Please enter your email for password reset.',
      sent: 'The password reset email has been sent. Please check your inbox.',
    },
    resetPassword: {
      oldPassword: 'Old Password',
      newPassword: 'New Password',
      confirmPassword: 'Confirm New Password',
      confirm: 'Confirm',
      oldPasswordRequired: 'Old password is required',
      passwordRequired: 'Password is required',
      confirmPasswordRequired: 'Confirm password is required',
      passwordNotMatch: 'Confirm password do not match!',
      resetPasswordSuccess: 'Reset password successfully, please log in again!',
    },
    improveInfo: {
      google: {
        title: 'Set up your account',
        signUp: 'Sign Up',
        confirm: 'Confirm',
        verify: {
          title: 'Verify your identity',
          tip: 'Verify your identity by entering your password for your EMQ Account below',
          emailTip: "This is your Google email address we've matched to your EMQ Account",
        },
      },
      github: {
        title: 'Set up your account',
        signUp: 'Sign Up',
        confirm: 'Confirm',
        verify: {
          title: 'Verify your identity',
          tip: 'Verify your identity by entering your password for your EMQ Account below',
          emailTip: "This is your GitHub email address we've matched to your EMQ Account",
        },
      },
    },
    asideDefault: {
      title: 'Modern <br /> Data Infrastructure <br /> for IoT',
    },
    asideSignup: {
      cloud: {
        title: 'Fully Managed MQTT Service for IoT',
        cloudProviderList: ['aws', 'azure', 'google-cloud'],
        freeTrial: 'Up to 14-Day Free Trial',
        noCreditCard: 'No credit card required',
        features: [
          'Fully managed MQTT cloud service',
          'Connect your IoT devices to everything',
          'Run Anywhere without vendor lock-in',
        ],
      },
      xmeter: {
        title: 'Fully Managed MQTT Load Testing Service',
        freeTrial: 'Free Trial',
        noCreditCard: 'No credit card required',
        features: [
          'Configure MQTT scenarios in 3 steps, launch load testing with one click.',
          'Designed specifically for IoT applications, supporting millions of simulated connections and message throughput.',
          'Highly automated deployment of test resources, clear and manageable costs.',
        ],
      },
    },
    smsCode: {
      name: 'SMS Code',
      send: 'Get SMS Code',
      sending: 'Get SMS Code',
      success: 'SMS code sent successfully',
      fail: "We couldn't send the SMS code. Please try again",
      required: 'SMS code is required',
      invalid: 'Invalid SMS code',
    },
    emailVerifyCode: {
      name: 'Verification Code',
      send: 'Get Code',
      sending: 'Get Code',
      success: 'Verification code sent successfully',
      fail: "We couldn't send the verification code. Please try again",
      required: 'Verification code is required',
      invalid: 'Invalid Verification code',
    },
    ruleTips: {
      fullName: 'Full Name is required',
      userName: 'Full Name is required',
      firstName: 'First Name is required',
      lastName: 'Last Name is required',
      organization: 'Organization is required',
      company: 'Company is required',
      country: 'Country or Region is required',
      os: 'OS is required',
      email: 'Email is required',
      emailNotValid: 'Invalid email',
      emailVerifyCode: 'Verification is required',
      emailVerifyCodeNotValid: 'Invalid verification code',
      password: 'Password is required',
      passwordNotValid: 'Password you entered is insecure',
      phone: 'Phone number is required',
      phoneNotValid: 'Invalid phone number',
      verifyCode: 'SMS code is required',
      verifyCodeNotValid: 'Invalid SMS code',
      agreement: 'Please accept the terms to continue',
    },
  },
}
