export default {
  'cloud-pricing': {
    title: 'EMQX Cloud料金プラン',
    // TODO: Need to translate the following content
    description:
      'We offer flexible EMQX Cloud plans for all your needs with a pay-as-you-go model. Free trial available.',
    // TODO: end
    banner: {
      title: '料金プラン',
      subTitle: '独自の開発者でも、グローバルな業界リーダーでも、適切なEMQX Cloud製品を見つけることができます。',
      pricingDetail: '料金詳細',
    },
    // TODO: Need to translate the following content
    plans: [
      {
        title: 'Serverlessタイプ',
        desc: [
          'Scalable and secure serverless MQTT broker you can get in seconds.',
          'Up to 1,000 sessions {0}, only pay as you go. Total free under free quota.',
        ],
        sessionsTip:
          'The number of sessions is calculated by adding the number of connected clients and the disconnected clients with sessions retained in the broker.',
        content: [
          {
            title: 'Forever free',
            list: [
              {
                title: '1 million session minutes / month',
                desc: [
                  'One session minute stands for one connection to the deployment in the span of a minute.',
                  '1 million session minutes are approximately 23 devices stay connected for one month. Equation: 23 * 60 * 24 *30 = 993,600. Or, 100 devices stay connected for 166 hours. Equation: 100 * 60 * 166 = 996,000.',
                ],
              },
              { title: '1 GB traffic / month' },
            ],
          },
          {
            title: 'Pay as you go',
            list: [
              {
                title: '$2.00 per additional million session minutes',
                desc: [
                  'One session minute stands for one connection to the deployment in the span of a minute.',
                  '1 million session minutes are approximately 23 devices stay connected for one month. Equation: 23 * 60 * 24 *30 = 993,600. Or, 100 devices stay connected for 166 hours. Equation: 100 * 60 * 166 = 996,000.',
                ],
              },
              { title: '$0.15 per GB for traffic' },
            ],
          },
        ],
        btnText: 'Get Started Free',
      },
      {
        title: 'Dedicated',
        desc: [
          'A fully managed MQTT broker in a dedicated cloud environment.',
          'With enhanced feature access, EMQX Dedicated is ideal for businesses of all sizes.',
        ],
        content: [
          {
            title: 'Billed monthly',
            list: [
              { title: 'Start at <strong>$0.18 / hour</strong>' },
              { title: 'Annual discount: <strong>15% off</strong>' },
            ],
          },
          {
            title: 'Enhanced features',
            list: [
              { title: 'Up to <strong>1 TB</strong> free traffic / month' },
              { title: 'Integration with other systems and services' },
              { title: '<strong>24 x 7</strong> expert support' },
            ],
          },
        ],
        btnText: '14-day Free Trial',
      },
      {
        title: 'BYOC',
        beta: 'Beta',
        bringOwnCloud: '(Bring Your Own Cloud)',
        desc: [
          'Host EMQX clusters on your own cloud, fully-managed by EMQX. Enjoy the best of both worlds: the convenience of the cloud with the security of your own data.',
        ],
        content: [
          'Dedicated EMQX Enterprise <strong>on your own cloud</strong>',
          'Your sensitive data <strong>never leaves</strong> your cloud',
          '<strong>Customizable</strong> MQTT server',
          '<strong>Fully managed</strong> by EMQX team',
          '<strong>24 x 7</strong> monitoring and technical support',
        ],
        btnText: 'Contact Us',
      },
    ],
    // TODO: end
    estimate: {
      title: '費用の見積もり',
      subTitle: '製品別の課金方式で、金額を見積り、確認します。',
      tabs: [
        {
          label: 'Serverless',
          value: 'serverless',
        },
        {
          label: 'カスタム版',
          value: 'basic',
        },
      ],
      serverless: {
        conns: '平均接続デバイス数',
        msgs: '各デバイス1分間に送信と受信されたメッセージの平均数',
        msgSize: '平均メッセージサイズ（バイト）',
        note: '料金推定は、1ヶ月間の継続的な接続シーンに基づいていますので、ご参考までに。詳細{detail}。',
        detail: '料金詳細',
      },
      version: 'バージョン：',
      region: '地域：',
      cloudPlatform: 'クラウドプラットフォーム：',
      specification: '仕様：',
      freeTraffic: '贈与トラフィック：',
      freePackage: '無料割当量：',
      pricing: '価格：',
      monthlyEstimate: '毎月の見積もり：',
      startForFree: '無料で使用開始',
      startDeployment: '導入開始',
      perMonth: ' / 月',
      chooseVersion: 'バージョンの選択',
      choosePlatform: 'クラウドプラットフォームの選択',
      chooseRegion: '地域の選択',
      chooseSpec: '仕様の選択',
      versionList: [
        { label: 'ベーシック版', value: 'basic' },
        { label: 'プロフェッショナル版', value: 'dedicated' },
      ],
      versionsDic: {
        basic: 'ベーシック版',
        dedicated: 'プロフェッショナル版',
      },
      platformIconsDic: {
        aliyun: 'icon-cloud-aliyun',
        aliyun_en: 'icon-cloud-aliyun',
        huawei: 'icon-cloud-huawei',
        aws_cn: 'icon-cloud-aws-cn',
        tencent: 'icon-cloud-tencent',
        aws: 'icon-cloud-aws',
        azure: 'icon-cloud-azure',
        gcp: 'icon-cloud-gcp',
      },
      moreThanMaxConn: '50,000接続を超える場合は、販売にお問い合わせください',
      saveMoney: '${price}を節約しました',
      trialTips: 'トライアル期間価格は、$0/時間で、トライアル期間14日間',
      hourPriceDesc: '時間単位での課金：${price} / 時間',
      yearPriceDesc: '年間課金：${price} / 年',
    },
    details: {
      title: '料金詳細',
      serverless: {
        title: 'Serverless',
        desc: '最もシンプルな構成で、EMQX Cloudサービスを手軽に開始できます。プロジェクトがまだ開始段階の業務、またはテスト評価に適しています。',
        pricingForRelease: '正規版料金の課金ルールによって、Betaテスト期間は無料トライアルです。',
        connectivity:
          '接続：$2.00 百万毎接続分（1接続分は1クライアント接続1分の計測単位、1分未満は1分で計算します。接続数には、保留セッションのオフラインクライアント数が含まれます。） ',
        traffic:
          'トラフィック：$0.15 / GB （トラフィックは、すべての流入および流出メッセージの総トラフィックを統計します）',
        freePackage: '無料割当量：毎月、百万の接続分数、および1GBのトラフィックを提供します。',
        seeExample: '価格確認の例',
        table: {
          head: [
            '接続シーン',
            '接続数',
            '毎分間に送信と受信するメッセージ数',
            'メッセージのサイズ（バイト）',
            '接続費（$）',
            'トラフィック費（$）',
            '総費用（$）',
          ],
          body: [
            [
              'シーン1：小規模な使用量であり、接続、情報とメッセージのサイズが小さい。',
              '20',
              '5',
              '200',
              '0',
              '0',
              '0',
            ],
            ['シーン2： 接続量が小さく、各メッセージのサイズが大きい。', '20', '5', '5,000', '0', '2.87', '2.87'],
            ['シーン3： 標準使用量、一般的なメッセージサイズです。', '100', '5', '300', '6.64', '0.75', '7.39'],
            ['シーン4： 大規模な接続数だが、メッセージ量が少ない。', '1,000', '0.1', '300', '84.40', '0.03', '84.43'],
          ],
        },
        estimateBasedOn: '見積の料金は、クライアントが１ヶ月接続し続けるシーンに基づいて推測するものです。',
      },
      dedicated: {
        title: 'カスタム版',
        pricingDetails: '料金詳細',
        standard: {
          title: 'ベーシック版',
          desc: '標準的なスループットとコンカレント量の業務シーンにおける独立したMQTTサービスに適しています。 ',
          table: {
            head: ['1時間の価格', '$0.18', '$0.50', '$0.88'],
            body: [
              ['接続制限', '1,000', '5,000', '10,000'],
              ['TPS制限', '1,000', '5,000', '5,000'],
              ['無料トラフィック（毎月）', '100 GB', '100 GB', '100 GB'],
              ['トラフィックオーバー', '$0.15 / GB', '$0.15 / GB', '$0.15 / GB'],
            ],
          },
        },
        professional: {
          title: 'プロフェッショナル版',
          desc: '高可用性のMQTTクラスタサービスは、プロダクション環境でのトライアルに最適な選択です。リアルタイムデータ処理、データ持続化、メッセージ配信、VPCピア接続（プライベートネットワーク）などの高度な機能をサポートします。',
          tips: '接続数が5万以上の場合、または他のニーズがある場合は、{contactUs}',
          contactUs: 'お問い合わせください',
          table: {
            head: ['1時間の価格', '$0.36', '$0.99', '$1.49', '$3.99'],
            body: [
              ['接続制限', '1,000', '5,000', '10,000', '50,000'],
              ['TPS制限', '1,000', '10,000', '20,000', '50,000'],
              ['無料トラフィック（毎月）', '100 GB', '100 GB', '100 GB', '1 TB'],
              ['トラフィックオーバー', '$0.15 / GB', '$0.15 / GB', '$0.15 / GB', '$0.15 / GB'],
            ],
          },
        },
      },
    },
    features: {
      title: '機能の詳細',
      serverless: 'Serverless',
      dedicated: 'カスタム版',
      standard: 'ベーシック版',
      professional: 'プロフェッショナル版',
      list: [
        {
          titleText: 'パブリッククラウドプラットフォーム',
          isSubhead: true,
        },
        {
          titleText: 'アリババ・クラウド',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'ファーウェイ・クラウド',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'テンセント・クラウド',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'AWS技術',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'サポートするプロトコル',
          isSubhead: true,
        },
        {
          titleText: 'MQTT v3.1, v3.1.1, v5.0',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'Port：mqtt, ws',
          serverless: 'notSupport',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'Port：mqtt over TLS, ws over TLS',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'WebSocket',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'MQTT-SN',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'CoAP',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'LwM2M',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: '接続',
          isSubhead: true,
        },
        {
          titleText: 'VPCピア接続（プライベートネットワーク）',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'プライベートネットワーク接続（アリババ・クラウド）',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'NATゲートウェイ',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'イントラネット負荷バランス ',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: '機能特徴',
          isSubhead: true,
        },
        {
          titleText: 'QoS 0,1,2',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'メッセージの保持',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: '遺言メッセージ',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: '共有サブスクライブ',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'ユーザー名とパスワード認証',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'クライアントとトピックアクセス制御',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'メトリック監視',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'プロジェクト管理',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'ロール権限管理',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: '領収書管理',
          serverless: 'support',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: '企業SSL証明書',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'サードパーティのデータソース認証と承認 ',
          serverless: 'notSupport',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'ログ',
          serverless: 'notSupport',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'データ統合',
          isSubhead: true,
        },
        {
          titleText: 'SQLベースのデータ処理',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'メッセージの再パブリッシュ',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'メッセージブリッジ',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'WebHook',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'Kafka',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'RabbitMQ',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'RocketMQ',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'Pulsar',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'MySQL',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'PostgreSQL',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'MongoDB',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'Redis',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'Cassandra',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'DynamoDB',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'ClickHouse',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'OpenTSDB',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'InfluxDB',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'TimescaleDB',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'Oracle DB',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'SQL Server',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'DolphinDB',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'TDengine',
          isSubTitle: true,
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: '付加価値サービス',
          isSubhead: true,
        },
        {
          titleText: 'シャドウサービス',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'カスタム関数',
          serverless: 'notSupport',
          standard: 'notSupport',
          dedicated: 'support',
        },
        {
          titleText: 'トラフィックパッケージ',
          serverless: 'notSupport',
          standard: 'support',
          dedicated: 'support',
        },
        {
          titleText: 'サービスとサポート',
          isSubhead: true,
        },
        {
          titleText: 'SLA レベル',
          serverless: '99.9%',
          standard: '99.95%',
          dedicated: '99.99%',
        },
        {
          titleText: 'テクニカルサポート',
          serverless: '-',
          standard: '8/5',
          dedicated: '24/7',
        },
        {
          titleText: '複数の可用地域の導入',
          serverless: '8 x 5',
          standard: '8 x 5',
          dedicated: '24 x 7',
        },
      ],
    },
    start: {
      title: '準備はできていますか。',
      desc: 'すぐにMQTTサービスをを所有します。',
      freeTrial: '無料トライアル',
    },
  },
}
