export default {
  licenses: {
    resetPassword: 'Reset Password',
    signOut: 'Sign Out',
    freeTrialEMQXEnterprise: 'Free Trial EMQX Enterprise',
    freeTrialEdge: 'Free Trial Edge Stack Mangement',
    numberOfConnections: 'Number of connections',
    licenseExpiration: 'License expiration',
    days: 'days',
    createLicense: 'Create License',
    createSuccess: 'The license created successfully',
    creatFail: 'The license created failed',
    downloadLicense: 'Download license',
    renewalLicense: 'Renewal license',
    notExpired: 'License has not expired yet',
    over2Tiems: 'Over 2 times',
    renewalSuccess: 'The license renewed successfully',
    renewalFail: 'The license renewed failed',
    tips: 'Tips',
    contactUsTips: 'Your Licence has been renewed for more than 2 times. Please {0}.',
    contactUs: 'contact us',
    creatDate: 'Creation date',
    updateDate: 'Update date',
    plugins: 'Plugins',
    operations: 'Operations',
    nodeNumber: 'Management node number',
    dataPoints: 'Neuron data points',
    edgeReadme:
      "Edge management suite license usage instructions\n\nEdge-manager users\n\n1. Click the 'Download License' button to open the downloaded license.zip archive;\n2. Open the management platform of Edge from the browser, click the 'License' menu in the left menu to access the administration page;\n3. Click the 'Upload' button, select the neuron.lic file in the license archive in the first step and confirm the upload;\n4. For the user who needs to update their license, click the 'Update' button in the top right corner and upload the downloaded neuron.lic file again. \n\nNote: For the user who needs to use Neuron in the Edge management platform, they need to click the 'Neuron Apply' button in the top right corner to apply the License information to the Neuron instance (this is also required when updating the license).\n\nNeuron users\n\n1. Click the 'Download License' button to open the downloaded license.zip archive;\n2. Select the License item in the 'Administration' menu in the top menu bar;\n3. Click the 'Upload' button in the pop-up box, select the neuron.lic file in the license archive in the first step and confirm the upload.",
  },
}
