export default {
  resources: {
    title: 'Resources',
    description: 'Explore all kinds of resources, gain insight into the world of EMQ and the IoT.',
    pageName: 'Resources',
    headline: 'Videos, White Papers and Presentations',
    headlineDescription: 'Explore all kinds of resources, gain insight into the world of EMQ and the IoT.',
    allRes: 'All',
    videos: 'Videos',
    whitePapers: 'White Papers',
    presentations: 'Presentations',
    reports: 'Reports',
    viewDetail: 'Learn More',
  },
  resourcesDetail: {
    back: 'Back to Resources',
    downloadWhitePaper: 'Get the White Paper',
    downloadPresentations: 'Get the Presentation',
    downloadReport: 'Get the Report',
    downloadSlides: 'Get the Slides',
    downloadTips: 'The download URL will be sent to the email you filled in.',
    email: 'Email',
    userName: 'Full Name',
    company: 'Company',
    useCase: 'Use Case',
    downloadNow: 'Download Now',
    emailTips: 'Email is required',
    notValidEmail: 'Invalid email address',
    userNameTips: 'Full Name is required',
    companyTips: 'Company is required',
    useCaseTips: 'Use Case is required',
    successTips: 'The download URL has been sent to your mailbox, please check!',
  },
}
